### ISSUE TITLE
NoMethodError - undefined method `class_name' for nil:NilClass: when using scoped through association

### ISSUE THREAD

**Issue by michaelnatkin** [Casecommons/pg_search#120]
I'm trying to follow this tip from the wiki:

"Right now, searching deeper than one association away is not supported. You can work around this by setting up a series of :through associations to point all the way through."

I have:

``` ruby
class Activity < ActiveRecord::Base
  has_many :equipment, class_name: ActivityEquipment, inverse_of: :activity, dependent: :destroy
  has_many :terminal_equipment, through: :equipment

  pg_search_scope :search_all, :against => [:title, :description], using: {tsearch: {prefix: true}}, associated_against: {terminal_equipment: [:title]}
end
```

when I try something like:

``` ruby
Activity.search_all("foo")
```

I get the stack trace below. Hopefully I'm just being a dolt, but I've tried varying this a number of different ways and am not able to perturb it :). If I just search against :equipment instead of :terminal_equipment, that works fine, but it doesn't have the fields I need there.

Stack trace:

```
NoMethodError - undefined method `class_name' for nil:NilClass:
  (gem) activerecord-3.2.11/lib/active_record/reflection.rb:530:in `derive_class_name'
  (gem) activerecord-3.2.11/lib/active_record/reflection.rb:127:in `class_name'
  (gem) activerecord-3.2.11/lib/active_record/reflection.rb:172:in `klass'
  (gem) activerecord-3.2.11/lib/active_record/reflection.rb:187:in `table_name'
  (gem) pg_search-0.5.7/lib/pg_search/configuration/association.rb:17:in `table_name'
  (gem) pg_search-0.5.7/lib/pg_search/configuration/association.rb:25:in `subselect_alias'
  (gem) pg_search-0.5.7/lib/pg_search/configuration/foreign_column.rb:20:in `expression'
  (gem) pg_search-0.5.7/lib/pg_search/configuration/column.rb:20:in `to_sql'
  (gem) pg_search-0.5.7/lib/pg_search/features/tsearch.rb:64:in `block in tsdocument'
  (gem) pg_search-0.5.7/lib/pg_search/features/tsearch.rb:63:in `map'
  (gem) pg_search-0.5.7/lib/pg_search/features/tsearch.rb:63:in `tsdocument'
  (gem) pg_search-0.5.7/lib/pg_search/features/tsearch.rb:88:in `tsearch_rank'
  (gem) pg_search-0.5.7/lib/pg_search/features/tsearch.rb:23:in `rank'
  (gem) pg_search-0.5.7/lib/pg_search/scope_options.rb:66:in `block in rank'
  (gem) pg_search-0.5.7/lib/pg_search/scope_options.rb:65:in `gsub'
  (gem) pg_search-0.5.7/lib/pg_search/scope_options.rb:65:in `rank'
  (gem) pg_search-0.5.7/lib/pg_search/scope_options.rb:14:in `apply'
  (gem) pg_search-0.5.7/lib/pg_search.rb:37:in `block in pg_search_scope'
  (gem) activerecord-3.2.11/lib/active_record/relation/delegation.rb:14:in `block in search_all'
```

**Comment by grossadamm** [comment]
thanks @michaelnatkin it helped me
