### ISSUE TITLE
Multisearch not working on a model that uses UUID for a primary key 

### ISSUE THREAD

**Issue by litch** [Casecommons/pg_search#142]
I have a model:

``` sql
CREATE TABLE businesses (
    id uuid DEFAULT uuid_generate_v4() NOT NULL,
    slug character varying(255),
    name character varying(255),
    phone_number character varying(255),
    website character varying(255),
    description text,
    latitude numeric(9,6),
    longitude numeric(9,6)
);
```

And am able to do a single-model search with it:

``` ruby
  pg_search_scope :search_by_properties, :against => [:website, :name, :description]
```

But when I try to do a multi-search using the following:

``` ruby
  multisearchable :against => [:website, :name, :description]
```

I get errors on model creation.  Attached is a log of where the actual object creation fails:

```
?> b = Business.create(name: "Foo")
   (0.2ms)  BEGIN
  SQL (7.2ms)  INSERT INTO "businesses" ("created_at", "name", "updated_at") VALUES ($1, $2, $3) RETURNING "id"  [["created_at", Tue, 19 Nov 2013 15:42:00 CST -06:00], ["name", "Foo"], ["updated_at", Tue, 19 Nov 2013 15:42:00 CST -06:00]]
  PgSearch::Document Load (0.9ms)  SELECT "pg_search_documents".* FROM "pg_search_documents" WHERE "pg_search_documents"."searchable_id" = $1 AND "pg_search_documents"."searchable_type" = $2 ORDER BY "pg_search_documents"."id" ASC LIMIT 1  [["searchable_id", "24c17e11-c6e6-4133-af42-36ae1b7f6651"], ["searchable_type", "Business"]]
  Business Load (1.1ms)  SELECT "businesses".* FROM "businesses" WHERE "businesses"."id" = $1 ORDER BY "businesses"."id" ASC LIMIT 1  [["id", 24]]
PG::InvalidTextRepresentation: ERROR:  invalid input syntax for uuid: "24"
: SELECT  "businesses".* FROM "businesses"  WHERE "businesses"."id" = $1  ORDER BY "businesses"."id" ASC LIMIT 1
   (0.2ms)  ROLLBACK
ActiveRecord::StatementInvalid: PG::InvalidTextRepresentation: ERROR:  invalid input syntax for uuid: "24"
: SELECT  "businesses".* FROM "businesses"  WHERE "businesses"."id" = $1  ORDER BY "businesses"."id" ASC LIMIT 1
    from /Users/litch/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:786:in `get_last_result'
    from /Users/litch/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:786:in `exec_cache'
    from /Users/litch/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:139:in `block in exec_query'
    from /Users/litch/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:435:in `block in log'
    from /Users/litch/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    from /Users/litch/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:430:in `log'
    from /Users/litch/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:137:in `exec_query'
    from /Users/litch/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:891:in `select'
    from /Users/litch/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:24:in `select_all'
    from /Users/litch/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/connection_adapters/abstract/query_cache.rb:63:in `select_all'
    from /Users/litch/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/querying.rb:36:in `find_by_sql'
    from /Users/litch/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/relation.rb:585:in `exec_queries'
    from /Users/litch/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/association_relation.rb:15:in `exec_queries'
    from /Users/litch/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/relation.rb:471:in `load'
    from /Users/litch/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/relation.rb:220:in `to_a'
    from /Users/litch/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/relation/finder_methods.rb:325:in `find_first'
... 35 levels...
    from /Users/litch/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/transactions.rb:326:in `block in with_transaction_returning_status'
    from /Users/litch/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `block in transaction'
    from /Users/litch/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:210:in `within_new_transaction'
    from /Users/litch/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `transaction'
    from /Users/litch/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/transactions.rb:209:in `transaction'
    from /Users/litch/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/transactions.rb:323:in `with_transaction_returning_status'
    from /Users/litch/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/transactions.rb:270:in `block in save'
    from /Users/litch/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/transactions.rb:281:in `rollback_active_record_state!'
    from /Users/litch/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/transactions.rb:269:in `save'
    from /Users/litch/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/persistence.rb:37:in `create'
    from (irb):5
    from /Users/litch/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.1/lib/rails/commands/console.rb:90:in `start'
    from /Users/litch/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.1/lib/rails/commands/console.rb:9:in `start'
    from /Users/litch/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.1/lib/rails/commands.rb:62:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'
```

**Comment by giedriusr** [comment]
@litch please close this issue if you have found the solution. Feel free to share your final solution what worked for you, so others could learn. Thanks.

**Comment by mabed** [comment]
Came across this issue! All my models are using UUID. How do you I tell the migration to generate a UUID type for the searchable_id column in the migration?

```
create_table :pg_search_documents, id: :uuid  do |t|
    t.text :content
references
   t.belongs_to :searchable, :polymorphic => true
    t.timestamps null: false
 end
```

**Comment by nertzy** [comment]
@giedriusr I don't want this issue closed if it represents a real problem in the gem. This is supposed to work *without* a workaround.

**Comment by jordonbiondo** [comment]
I think most people who are using uuids for keys are probably using them everywhere, it would be nice if there were just a note on the readme about needing to change the generated migration if that is the case.

For me I simply needed to change the `t.belongs_to :searchable...` line in the migration to include `:type => :uuid` before running it and was set.

**Comment by arcreative** [comment]
Seems to me it would be safer to have the `searchable_id` column be `varchar` and just use typecasting on index?  I definitely don't have integers nor UUIDs for my records, but `varchar` is able to represent both.

**Comment by reggieb** [comment]
> I think most people who are using uuids for keys are probably using them everywhere, it would be nice if there were just a note on the readme about needing to change the generated migration if that is the case.
> 
> For me I simply needed to change the `t.belongs_to :searchable...` line in the migration to include `:type => :uuid` before running it and was set.

I think if this information was added to the README this ticket could be closed!
