### ISSUE TITLE
Using acts_as_taggable_on association in associated_against throws error

### ISSUE THREAD

**Issue by jeffleeismyhero** [Casecommons/pg_search#188]
If I try to add an association created by acts_as_taggable_on I get `undefined method `fields' for nil:NilClass`. I can't seem to figure out how to work around this.

The pertinent code and a backtrace are below:

``` ruby
class Place < ActiveRecord::Base
  include PgSearch
  pg_search_scope :search_by_all_keywords,
    against: [:name],
    using: {
      tsearch: {
        dictionary: 'english',
        tsvector_column: 'tsv',
        any_word: false,
        normalization: 1
      }
    },
    associated_against: {
      tags: [:name]
    },
    ignoring: :accents

  acts_as_ordered_taggable_on :tags
end

```

``` ruby
undefined method `fields' for nil:NilClass
Exception `NoMethodError' at:
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/activerecord-3.2.19/lib/active_record/connection_adapters/postgresql_adapter.rb:663:in `block in exec_query'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/activesupport-3.2.19/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/activerecord-3.2.19/lib/active_record/connection_adapters/postgresql_adapter.rb:659:in `exec_query'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/activerecord-3.2.19/lib/active_record/connection_adapters/postgresql_adapter.rb:1262:in `select'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/database_statements.rb:18:in `select_all'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/query_cache.rb:63:in `select_all'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/database_statements.rb:24:in `select_one'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/database_statements.rb:30:in `select_value'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/activerecord-3.2.19/lib/active_record/relation/calculations.rb:250:in `execute_simple_calculation'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/activerecord-3.2.19/lib/active_record/relation/calculations.rb:215:in `perform_calculation'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/activerecord-3.2.19/lib/active_record/relation/calculations.rb:159:in `calculate'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/activerecord-3.2.19/lib/active_record/relation/calculations.rb:58:in `count'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/will_paginate-3.0.4/lib/will_paginate/active_record.rb:90:in `count'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/will_paginate-3.0.4/lib/will_paginate/active_record.rb:88:in `count'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/will_paginate-3.0.4/lib/will_paginate/active_record.rb:106:in `empty?'
app/controllers/places_controller.rb:518:in `search'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/actionpack-3.2.19/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/actionpack-3.2.19/lib/abstract_controller/base.rb:167:in `process_action'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/actionpack-3.2.19/lib/action_controller/metal/rendering.rb:10:in `process_action'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/actionpack-3.2.19/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:524:in `_run__3886381865151945808__process_action__776497265093921041__callbacks'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:405:in `__run_callback'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/actionpack-3.2.19/lib/abstract_controller/callbacks.rb:17:in `process_action'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/actionpack-3.2.19/lib/action_controller/metal/rescue.rb:29:in `process_action'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/actionpack-3.2.19/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/activesupport-3.2.19/lib/active_support/notifications.rb:123:in `block in instrument'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/activesupport-3.2.19/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/activesupport-3.2.19/lib/active_support/notifications.rb:123:in `instrument'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/actionpack-3.2.19/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/actionpack-3.2.19/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/activerecord-3.2.19/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/actionpack-3.2.19/lib/abstract_controller/base.rb:121:in `process'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/actionpack-3.2.19/lib/abstract_controller/rendering.rb:45:in `process'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/actionpack-3.2.19/lib/action_controller/metal/testing.rb:17:in `process_with_new_base_test'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/actionpack-3.2.19/lib/action_controller/test_case.rb:490:in `process'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/actionpack-3.2.19/lib/action_controller/test_case.rb:54:in `process'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/devise-2.2.3/lib/devise/test_helpers.rb:19:in `block in process'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/devise-2.2.3/lib/devise/test_helpers.rb:72:in `catch'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/devise-2.2.3/lib/devise/test_helpers.rb:72:in `_catch_warden'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/devise-2.2.3/lib/devise/test_helpers.rb:19:in `process'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/actionpack-3.2.19/lib/action_controller/test_case.rb:407:in `get'
test/functional/places_controller_test.rb:472:in `block (2 levels) in <class:PlacesControllerTest>'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/activesupport-3.2.19/lib/active_support/testing/setup_and_teardown.rb:36:in `block in run'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:491:in `_run__3552110268068551333__setup__4354085474940099418__callbacks'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:405:in `__run_callback'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:385:in `_run_setup_callbacks'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/jlee/.rbenv/versions/2.0.0-p353/gemsets/test_app/gems/activesupport-3.2.19/lib/active_support/testing/setup_and_teardown.rb:35:in `run'
```

**Comment by ddengler** [comment]
does not seem to be an issue anymore
