### ISSUE TITLE
RuntimeError: unsupported: Symbol with 4.2.0.beta1

### ISSUE THREAD

**Issue by olimart** [Casecommons/pg_search#189]
`Order.search_by_keyword('bruno')` throws error `RuntimeError: unsupported: Symbol`

Search used to work well with rails 4.1.4. Not sure how to debug.

```
from .rvm/gems/ruby-2.0.0-p353/gems/arel-6.0.0.beta1/lib/arel/visitors/to_sql.rb:726:in `unsupported'
from .rvm/gems/ruby-2.0.0-p353/gems/arel-6.0.0.beta1/lib/arel/visitors/reduce.rb:13:in `visit'
from .rvm/gems/ruby-2.0.0-p353/gems/arel-6.0.0.beta1/lib/arel/visitors/to_sql.rb:785:in `block in inject_join'
from .rvm/gems/ruby-2.0.0-p353/gems/arel-6.0.0.beta1/lib/arel/visitors/to_sql.rb:781:in `each'
from .rvm/gems/ruby-2.0.0-p353/gems/arel-6.0.0.beta1/lib/arel/visitors/to_sql.rb:781:in `each_with_index'
from .rvm/gems/ruby-2.0.0-p353/gems/arel-6.0.0.beta1/lib/arel/visitors/to_sql.rb:781:in `each'
from .rvm/gems/ruby-2.0.0-p353/gems/arel-6.0.0.beta1/lib/arel/visitors/to_sql.rb:781:in `inject'
from .rvm/gems/ruby-2.0.0-p353/gems/arel-6.0.0.beta1/lib/arel/visitors/to_sql.rb:781:in `inject_join'
from .rvm/gems/ruby-2.0.0-p353/gems/arel-6.0.0.beta1/lib/arel/visitors/to_sql.rb:463:in `visit_Arel_Nodes_NamedFunction'
from .rvm/gems/ruby-2.0.0-p353/gems/arel-6.0.0.beta1/lib/arel/visitors/reduce.rb:13:in `visit'
from .rvm/gems/ruby-2.0.0-p353/gems/arel-6.0.0.beta1/lib/arel/visitors/reduce.rb:7:in `accept'
from .rvm/gems/ruby-2.0.0-p353/gems/arel-6.0.0.beta1/lib/arel/nodes/node.rb:48:in `to_sql'
from .rvm/gems/ruby-2.0.0-p353/gems/pg_search-0.7.6/lib/pg_search/features/tsearch.rb:106:in `column_to_tsvector'
from .rvm/gems/ruby-2.0.0-p353/gems/pg_search-0.7.6/lib/pg_search/features/tsearch.rb:58:in `block in tsdocument'
from .rvm/gems/ruby-2.0.0-p353/gems/pg_search-0.7.6/lib/pg_search/features/tsearch.rb:57:in `map'
from .rvm/gems/ruby-2.0.0-p353/gems/pg_search-0.7.6/lib/pg_search/features/tsearch.rb:57:in `tsdocument'
from .rvm/gems/ruby-2.0.0-p353/gems/pg_search-0.7.6/lib/pg_search/features/tsearch.rb:83:in `tsearch_rank'
from .rvm/gems/ruby-2.0.0-p353/gems/pg_search-0.7.6/lib/pg_search/features/tsearch.rb:23:in `rank'
from .rvm/gems/ruby-2.0.0-p353/gems/pg_search-0.7.6/lib/pg_search/scope_options.rb:86:in `block in rank'
from .rvm/gems/ruby-2.0.0-p353/gems/pg_search-0.7.6/lib/pg_search/scope_options.rb:85:in `gsub'
from .rvm/gems/ruby-2.0.0-p353/gems/pg_search-0.7.6/lib/pg_search/scope_options.rb:85:in `rank'
from .rvm/gems/ruby-2.0.0-p353/gems/pg_search-0.7.6/lib/pg_search/scope_options.rb:17:in `apply'
from .rvm/gems/ruby-2.0.0-p353/gems/pg_search-0.7.6/lib/pg_search.rb:40:in `block in pg_search_scope'
from (irb):6
from .rvm/gems/ruby-2.0.0-p353/gems/railties-4.2.0.beta1/lib/rails/commands/console.rb:110:in `start'
from .rvm/gems/ruby-2.0.0-p353/gems/railties-4.2.0.beta1/lib/rails/commands/console.rb:9:in `start'
from .rvm/gems/ruby-2.0.0-p353/gems/railties-4.2.0.beta1/lib/rails/commands/commands_tasks.rb:68:in `console'
from .rvm/gems/ruby-2.0.0-p353/gems/railties-4.2.0.beta1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
from .rvm/gems/ruby-2.0.0-p353/gems/railties-4.2.0.beta1/lib/rails/commands.rb:17:in `<top (required)>'
from bin/rails:8:in `require'
```

**Comment by Protosac** [comment]
Just got this error myself performing a query. The code that started the error:

    def search
        q = params[:name]
        
        @encounters = Encounter.where(:all, :conditions => ["name LIKE %?%", q])
        render json: @encounters
      end
