### ISSUE TITLE
Search scope returns Array rather than ActiveRecord Relation

### ISSUE THREAD

**Issue by amnesia7** [Casecommons/pg_search#276]
I have the following search scope (using v1.0.5):
```
  include PgSearch

  pg_search_scope :keyword_search, against: {
                                      field1: 'A',
                                      field2: 'B',
                                      field3: 'D'
                                    },
                                    ignoring: :accents,
                                    using: {
                                      tsearch: {
                                        dictionary: 'english',
                                        tsvector_column: 'search_vector'
                                      }
                                    },
                                    ranked_by: ':tsearch'
```
which is called as part of a search class method; something along the lines of:
```
def self.search(query, foo)
  scoped = self.all
  scoped = scoped.keyword_search(query) if query.present?
  scoped = scoped.other_scope(foo) if foo.present?
  scoped
end
```
I don't seem to be allowed to chain any further scopes after `.keyword_search` because it seems to return an `Array`. Here's a similar [but unrelated] issue if it helps - http://stackoverflow.com/questions/12556715/undefined-method-on-class-method

I'm not sure if this issue existed before or not, it's just that I'm trying to merge a few filter methods together under my `.search` method and it didn't work. If I put my extra scopes before `.keyword_search` they all work fine but I can't put them after it.

Am I missing something or is there an issue here?

**Comment by amarshall** [comment]
Please include your ActiveRecord version and the actual error you’re receiving, and also mark line numbers in your code excerpt that correspond to line numbers given in the error backtrace.

**Comment by amnesia7** [comment]
@amarshall some more details here.

I'm using rails `4.1.14`.

Error message:
```
     Failure/Error: scoped = scoped.filter_by_params(params)
     
     NoMethodError:
       undefined method `filter_by_params' for #<Array:0xdf7bc0c>
     # ./app/models/post.rb:102:in `search'
     # ./spec/models/post_spec.rb:809:in `block (5 levels) in <top (required)>'
     # /home/me/.rvm/gems/ruby-2.0.0-p643@blog/gems/activesupport-4.1.14/lib/active_support/dependencies.rb:241:in `load'
     # /home/me/.rvm/gems/ruby-2.0.0-p643@blog/gems/activesupport-4.1.14/lib/active_support/dependencies.rb:241:in `block in load'
     # /home/me/.rvm/gems/ruby-2.0.0-p643@blog/gems/activesupport-4.1.14/lib/active_support/dependencies.rb:232:in `load_dependency'
     # /home/me/.rvm/gems/ruby-2.0.0-p643@blog/gems/activesupport-4.1.14/lib/active_support/dependencies.rb:241:in `load'
     # /home/me/.rvm/gems/ruby-2.0.0-p643@blog/gems/spring-commands-rspec-1.0.4/lib/spring/commands/rspec.rb:18:in `call'
     # /home/me/.rvm/gems/ruby-2.0.0-p643@blog/gems/spring-1.5.0/lib/spring/command_wrapper.rb:38:in `call'
     # /home/me/.rvm/gems/ruby-2.0.0-p643@blog/gems/spring-1.5.0/lib/spring/application.rb:183:in `block in serve'
     # /home/me/.rvm/gems/ruby-2.0.0-p643@blog/gems/spring-1.5.0/lib/spring/application.rb:156:in `fork'
     # /home/me/.rvm/gems/ruby-2.0.0-p643@blog/gems/spring-1.5.0/lib/spring/application.rb:156:in `serve'
     # /home/me/.rvm/gems/ruby-2.0.0-p643@blog/gems/spring-1.5.0/lib/spring/application.rb:131:in `block in run'
     # /home/me/.rvm/gems/ruby-2.0.0-p643@blog/gems/spring-1.5.0/lib/spring/application.rb:125:in `loop'
     # /home/me/.rvm/gems/ruby-2.0.0-p643@blog/gems/spring-1.5.0/lib/spring/application.rb:125:in `run'
     # /home/me/.rvm/gems/ruby-2.0.0-p643@blog/gems/spring-1.5.0/lib/spring/application/boot.rb:18:in `<top (required)>'
     # -e:1:in `<main>'
```
Here's the search method (trimmed down to enough to make it break). See above comment for `keyword_search` scope code:
```
  def self.search(params)
    query = params[:q]

    scoped = self.all
    if query.present?
      # other stuff in here but breaks with and without it
      scoped = scoped.keyword_search(query) if query.present?
    end
    scoped = scoped.filter_by_params(params) # here's where it fails (line 102)!
    scoped
  end
```
Here's the filter_by_params method (with logic removed to make it easier):
```
  def self.filter_by_location(params)
    scoped = self.all
    # logic in here but breaks with and without it
    scoped
  end
```
Rspec test that fails (one of many that all work if I put `filter_by_params` before `if query.present?` / `keyword_search` scope). Other failing tests include ones that just call `search` and check that `posts` includes specific posts:
```
      it 'should call .keyword_search with search query' do
        posts = Post
        expect(posts)
          .to receive(:keyword_search)
          .with('web')
          .and_return([web_post])
        posts.search({ q: 'web' }) # here's where it fails (line 809)!
      end
```

**Comment by amarshall** [comment]
Your test appears to be the problem: `.and_return([web_post])`. You’re stubbing the PgSearch scope and causing it to return an Array instead of an ActiveRecord::Relation.

**Comment by amnesia7** [comment]
@amarshall that seems to have sorted those out by removing the square brackets which works in this case because this test is only returning a single result. 
Any ideas how to make `and_return` test for multiple activerecord results or is that a question for rspec folk?
