### ISSUE TITLE
PG::UndefinedTable: ERROR:  relation does not exist

### ISSUE THREAD

**Issue by jankeesvw** [Casecommons/pg_search#299]
I'm building a fairly simple search but I run into a beginners problem (I think), I added this to my `Document` model:

```ruby
class Document < ActiveRecord::Base
  include PgSearch
  pg_search_scope :search, against: [:subject, :number], associated_against: {
    sender: :name,
    receiver: :name
  }
```

It works perfectly from the Rails console, but when I'm writing my test it gives me an error, this is my test:

```ruby

  describe ".search" do
    it "can search for document subject" do
      human = create(:document, subject: "Human")
      create(:document, subject: "Robot")

      expect(Document.search("Human")).to eq human
    end
  end
```

I then see this error:

```
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "pg_search_documents" does not exist
LINE 5:                WHERE a.attrelid = '"pg_search_documents"'::r...
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"pg_search_documents"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum

./app/models/document.rb:77:in `check_for_duplicate_document'
./spec/models/document_spec.rb:9:in `block (3 levels) in <top (required)>'
-e:1:in `load'
-e:1:in `<main>'
------------------
--- Caused by: ---
PG::UndefinedTable:
  ERROR:  relation "pg_search_documents" does not exist
  LINE 5:                WHERE a.attrelid = '"pg_search_documents"'::r...
                                            ^
  ./app/models/document.rb:77:in `check_for_duplicate_document'
```

I hope someone can point me in the direction of the solution, ✨

**Comment by nertzy** [comment]
Please post the source for your `Document#check_for_duplicate_document` method.

The last line is telling you to look there:

```
  ./app/models/document.rb:77:in `check_for_duplicate_document'
```

**Comment by jankeesvw** [comment]
This is the method @nertzy:

```ruby
  def check_for_duplicate_document
    possible_duplicate = Document.where(
      user_id: user_id,
      sender: sender_id,
      receiver: receiver_id,
      subject: subject,
      date: date
    )

    possible_duplicate = possible_duplicate.where("id <> ?", id) if persisted?
    errors.add(:base, :document_already_exists) if possible_duplicate.present? && processed?
  end
