### ISSUE TITLE
undefined method `to_sym'

### ISSUE THREAD

**Issue by Pitometsu** [Casecommons/pg_search#303]
Error when I try to put Hash by `:tsearch` instead of use plain array without additional customizations.
What did do I wrong and is there any known workarounds?

> undefined method `to_sym' for {:tsearch=>{:prefix=>true}}:Hash Did you mean? to_s to_yaml to_set

```ruby
# controller
def search
      result = User.search_by_login params[:search][:query]
```
```ruby
# model
  pg_search_scope :search_by_login, against: [:name, :email],
                                    using: [:trigram, :dmetaphone,
                                            :tsearch => { :prefix => true }],
                                    ignoring: [:accents]
```
```
/usr/local/rvm/gems/ruby-2.3.0/bundler/gems/pg_search-e4e2ed236690/lib/pg_search/scope_options.rb:147:in `feature_for'
/usr/local/rvm/gems/ruby-2.3.0/bundler/gems/pg_search-e4e2ed236690/lib/pg_search/scope_options.rb:114:in `block in conditions'
/usr/local/rvm/gems/ruby-2.3.0/bundler/gems/pg_search-e4e2ed236690/lib/pg_search/scope_options.rb:113:in `map!'
/usr/local/rvm/gems/ruby-2.3.0/bundler/gems/pg_search-e4e2ed236690/lib/pg_search/scope_options.rb:113:in `conditions'
/usr/local/rvm/gems/ruby-2.3.0/bundler/gems/pg_search-e4e2ed236690/lib/pg_search/scope_options.rb:103:in `subquery'
/usr/local/rvm/gems/ruby-2.3.0/bundler/gems/pg_search-e4e2ed236690/lib/pg_search/scope_options.rb:170:in `rank_join'
/usr/local/rvm/gems/ruby-2.3.0/bundler/gems/pg_search-e4e2ed236690/lib/pg_search/scope_options.rb:20:in `apply'
/usr/local/rvm/gems/ruby-2.3.0/bundler/gems/pg_search-e4e2ed236690/lib/pg_search.rb:39:in `block in pg_search_scope'
app/controllers/users_controller.rb:80:in `search'
```

**Comment by nertzy** [comment]
pg_search doesn't support having different types of objects in an Array as the value of `:using`.

Try this instead:
```ruby
  pg_search_scope :search_by_login, against: [:name, :email],
                                    using: [
                                      :trigram => {},
                                      :dmetaphone => {},
                                      :tsearch => { :prefix => true }
                                    },
                                    ignoring: [:accents]
```

**Comment by Pitometsu** [comment]
@nertzy thanks a lot, could you update documentations part for this?
