### ISSUE TITLE
PG::UndefinedObject: ERROR:  text search configuration "????" does not exist

### ISSUE THREAD

**Issue by zw963** [Casecommons/pg_search#334]
I create a new config with a third part chinese search engine, named: `ershou_web_pgsearch`

It worked when I tried in psql

```sql
postgres=# select to_tsvector('ershou_web_pgsearch','ruby程序员需要不停地学习新知识，努力提高自己的技术水平。') ;
                                                         --------------------------------------------------------------------------------------------------------------
 'ruby':1 '不停':4 '努力':9 '地':5 '学习':6 '技术':11 '提高':10 '新知':7 '水平':12 '程序员':2 '识':8 '需要':3
(1 row)
```

But when I use in my model, with following code:

### Model

```rb
include PgSearch

  pg_search_scope(
    :pg_query,
    against: [
      :title, :description, :address,
      :detected_labels, :detected_labels_cn, :clicks_count,
      :updated_at, :type
    ],
    using: {
      tsearch: {
        dictionary: 'ershou_web_pgsearch'
      }
    }
  )
```

### Controller

```rb
def index1
    keyword = params[:q]

    @goods_items = GoodsItem.pg_query(keyword)
    render 'index'
  end
```

When I run test (in test mode), get following error.

```sh
Error:
SearchControllerTest#test_: #index1 should OK1. :
ActionView::Template::Error: PG::UndefinedObject: ERROR:  text search configuration "ershou_web_pgsearch" does not exist
LINE 1: ...tems"."id" AS pg_search_id, (ts_rank((to_tsvector('ershou_we...
                                                             ^
: SELECT "goods_items".* FROM "goods_items" INNER JOIN (SELECT "goods_items"."id" AS pg_search_id, (ts_rank((to_tsvector('ershou_web_pgsearch', coalesce("goods_items"."title"::text, '')) || to_tsvector('ershou_web_pgsearch', coalesce("goods_items"."description"::text, '')) || to_tsvector('ershou_web_pgsearch', coalesce("goods_items"."address"::text, '')) || to_tsvector('ershou_web_pgsearch', coalesce("goods_items"."detected_labels"::text, '')) || to_tsvector('ershou_web_pgsearch', coalesce("goods_items"."detected_labels_cn"::text, '')) || to_tsvector('ershou_web_pgsearch', coalesce("goods_items"."clicks_count"::text, '')) || to_tsvector('ershou_web_pgsearch', coalesce("goods_items"."updated_at"::text, '')) || to_tsvector('ershou_web_pgsearch', coalesce("goods_items"."type"::text, ''))), (to_tsquery('ershou_web_pgsearch', ''' ' || '大衣' || ' ''')), 0)) AS rank FROM "goods_items" WHERE (((to_tsvector('ershou_web_pgsearch', coalesce("goods_items"."title"::text, '')) || to_tsvector('ershou_web_pgsearch', coalesce("goods_items"."description"::text, '')) || to_tsvector('ershou_web_pgsearch', coalesce("goods_items"."address"::text, '')) || to_tsvector('ershou_web_pgsearch', coalesce("goods_items"."detected_labels"::text, '')) || to_tsvector('ershou_web_pgsearch', coalesce("goods_items"."detected_labels_cn"::text, '')) || to_tsvector('ershou_web_pgsearch', coalesce("goods_items"."clicks_count"::text, '')) || to_tsvector('ershou_web_pgsearch', coalesce("goods_items"."updated_at"::text, '')) || to_tsvector('ershou_web_pgsearch', coalesce("goods_items"."type"::text, ''))) @@ (to_tsquery('ershou_web_pgsearch', ''' ' || '大衣' || ' '''))))) AS pg_search_b9fe35d73f72a3d2eee7be ON "goods_items"."id" = pg_search_b9fe35d73f72a3d2eee7be.pg_search_id ORDER BY pg_search_b9fe35d73f72a3d2eee7be.rank DESC, "goods_items"."id" ASC
    app/views/api/v1/search/index.json.jbuilder:5:in `block in _app_views_api_v__search_index_json_jbuilder__121368469391496630_72323940'
    app/views/api/v1/search/index.json.jbuilder:4:in `_app_views_api_v__search_index_json_jbuilder__121368469391496630_72323940'
    app/controllers/api/v1/search_controller.rb:15:in `index1'
    test/controllers/api/v1/search_controller_test.rb:416:in `block (2 levels) in <class:SearchControllerTest>
```

**Comment by zw963** [comment]
Rails version: 5.0.0.1
Ruby version: 2.2.4

Thanks.

**Comment by zw963** [comment]
Hi, I found this config not exist error is only not worked in test mode,

in development, it worked pretty well.

I think ,it is maybe caused by test only load table schema from db/schema.rb
so, it not know the the correct create config SQL is executed.
Though, I am not verified.

thanks

**Comment by zw963** [comment]
Hi, I run create config SQL manually in my test, it worked now.

Thanks.
