### ISSUE TITLE
Aborting migration after upgrading to Rails 5.1

### ISSUE THREAD

**Issue by erikse** [Casecommons/pg_search#361]
It looks like Rails 5.1 requires a migration to specify a Rails version when inheriting from `ActiveRecord::Migration`, and aborts execution if it finds one without it. 

Trying to run a migration generated with this gem in Rails 5.1 results in:

```
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreatePgSearchDocuments < ActiveRecord::Migration[4.2]
/Users/erik/.rvm/gems/ruby-2.3.4/gems/activerecord-5.1.1/lib/active_record/migration.rb:525:in `inherited'
/Users/erik/Coding/erikse/simpsons/db/migrate/20161028030540_create_pg_search_documents.rb:1:in `<top (required)>'
/Users/erik/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require'
/Users/erik/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `block in require'
/Users/erik/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:258:in `load_dependency'
/Users/erik/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require'
/Users/erik/.rvm/gems/ruby-2.3.4/gems/activerecord-5.1.1/lib/active_record/migration.rb:962:in `load_migration'
/Users/erik/.rvm/gems/ruby-2.3.4/gems/activerecord-5.1.1/lib/active_record/migration.rb:958:in `migration'
/Users/erik/.rvm/gems/ruby-2.3.4/gems/activerecord-5.1.1/lib/active_record/migration.rb:953:in `disable_ddl_transaction'
/Users/erik/.rvm/gems/ruby-2.3.4/gems/activerecord-5.1.1/lib/active_record/migration.rb:1305:in `use_transaction?'
/Users/erik/.rvm/gems/ruby-2.3.4/gems/activerecord-5.1.1/lib/active_record/migration.rb:1297:in `ddl_transaction'
/Users/erik/.rvm/gems/ruby-2.3.4/gems/activerecord-5.1.1/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/Users/erik/.rvm/gems/ruby-2.3.4/gems/activerecord-5.1.1/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
/Users/erik/.rvm/gems/ruby-2.3.4/gems/activerecord-5.1.1/lib/active_record/migration.rb:1200:in `each'
/Users/erik/.rvm/gems/ruby-2.3.4/gems/activerecord-5.1.1/lib/active_record/migration.rb:1200:in `migrate_without_lock'
/Users/erik/.rvm/gems/ruby-2.3.4/gems/activerecord-5.1.1/lib/active_record/migration.rb:1148:in `block in migrate'
/Users/erik/.rvm/gems/ruby-2.3.4/gems/activerecord-5.1.1/lib/active_record/migration.rb:1317:in `with_advisory_lock'
/Users/erik/.rvm/gems/ruby-2.3.4/gems/activerecord-5.1.1/lib/active_record/migration.rb:1148:in `migrate'
/Users/erik/.rvm/gems/ruby-2.3.4/gems/activerecord-5.1.1/lib/active_record/migration.rb:1007:in `up'
/Users/erik/.rvm/gems/ruby-2.3.4/gems/activerecord-5.1.1/lib/active_record/migration.rb:985:in `migrate'
/Users/erik/.rvm/gems/ruby-2.3.4/gems/activerecord-5.1.1/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/Users/erik/.rvm/gems/ruby-2.3.4/gems/activerecord-5.1.1/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/Users/erik/.rvm/gems/ruby-2.3.4/gems/railties-5.1.1/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/Users/erik/.rvm/gems/ruby-2.3.4/gems/railties-5.1.1/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/erik/.rvm/gems/ruby-2.3.4/gems/railties-5.1.1/lib/rails/command.rb:46:in `invoke'
/Users/erik/.rvm/gems/ruby-2.3.4/gems/railties-5.1.1/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreatePgSearchDocuments < ActiveRecord::Migration[4.2]
```
Just changing that line from:
```
class CreatePgSearchDocuments < ActiveRecord::Migration
```
to include a Rails major.minor version
```
class CreatePgSearchDocuments < ActiveRecord::Migration[5.0]
```
and it runs normally again.

Seems like a common issue with other gems implementing a change to the migration generator, e.g: https://github.com/collectiveidea/delayed_job_active_record/commit/cac86ac506111cbe0a07c87d3d541214fabfb131

**Comment by erikse** [comment]
Thanks for merging PR, closing
