### ISSUE TITLE
ActiveRecord::RecordInvalid: Validation failed: [object] must exist

### ISSUE THREAD

**Issue by KeithP** [Casecommons/pg_search#368]
After running `Bundle update` we advanced to pg_search 2.1.0 ( was 2.0.1) and Rails 5.1.3 ( was 5.1.2 ).
Now most of the RSpec tests are failing. 

We are running psql (PostgreSQL) 9.3.15

An example test failure is below. If we 'fix' this test for example by adding `optional: true` to a belongs_to class declaration then more failures surface. It is as if the event hooks in Rails such as `before_save` are somehow messed up and are no longer running ( maybe ? ) 

I know this is a bit sketchy on detail but maybe someone else has a similar issue and can add insight.
Many thanks for your work on this fantastic gem.

```
Market::Stock search_all finds all funds
Failure/Error: self.where( user_id: user_id, category: 2, stock_id: 1 ).first_or_create!

ActiveRecord::RecordInvalid:
  Validation failed: Stock must exist
# /home/rof/cache/bundler/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/validations.rb:78:in `raise_validation_error'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/validations.rb:50:in `save!'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/attribute_methods/dirty.rb:43:in `save!'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/transactions.rb:313:in `block in save!'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/transactions.rb:384:in `block in with_transaction_returning_status'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/abstract/database_statements.rb:233:in `transaction'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/transactions.rb:210:in `transaction'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/transactions.rb:313:in `save!'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/suppressor.rb:46:in `save!'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/persistence.rb:51:in `create!'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/relation.rb:156:in `block in create!'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/relation.rb:336:in `scoping'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/relation.rb:156:in `create!'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/relation.rb:164:in `first_or_create!'
# ./app/models/manage/market_definition.rb:47:in `add_default_white_list_for'
# ./app/models/user.rb:138:in `do_after_save'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/callbacks.rb:413:in `block in make_lambda'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/callbacks.rb:235:in `block in halting_and_conditional'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/callbacks.rb:511:in `block in invoke_after'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/callbacks.rb:511:in `each'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/callbacks.rb:511:in `invoke_after'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/callbacks.rb:132:in `run_callbacks'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/callbacks.rb:827:in `_run_save_callbacks'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/callbacks.rb:336:in `create_or_update'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/persistence.rb:162:in `save!'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/validations.rb:50:in `save!'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/attribute_methods/dirty.rb:43:in `save!'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/transactions.rb:313:in `block in save!'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/transactions.rb:384:in `block in with_transaction_returning_status'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/transactions.rb:210:in `transaction'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/transactions.rb:313:in `save!'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/suppressor.rb:46:in `save!'
# /home/rof/cache/bundler/ruby/2.3.0/gems/factory_girl-4.8.0/lib/factory_girl/configuration.rb:18:in `block in initialize'
# /home/rof/cache/bundler/ruby/2.3.0/gems/factory_girl-4.8.0/lib/factory_girl/evaluation.rb:15:in `create'
# /home/rof/cache/bundler/ruby/2.3.0/gems/factory_girl-4.8.0/lib/factory_girl/strategy/create.rb:12:in `block in result'
# /home/rof/cache/bundler/ruby/2.3.0/gems/factory_girl-4.8.0/lib/factory_girl/strategy/create.rb:9:in `tap'
# /home/rof/cache/bundler/ruby/2.3.0/gems/factory_girl-4.8.0/lib/factory_girl/strategy/create.rb:9:in `result'
# /home/rof/cache/bundler/ruby/2.3.0/gems/factory_girl-4.8.0/lib/factory_girl/factory.rb:42:in `run'
# /home/rof/cache/bundler/ruby/2.3.0/gems/factory_girl-4.8.0/lib/factory_girl/factory_runner.rb:29:in `block in run'
# /home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/notifications.rb:168:in `instrument'
# /home/rof/cache/bundler/ruby/2.3.0/gems/factory_girl-4.8.0/lib/factory_girl/factory_runner.rb:28:in `run'
# /home/rof/cache/bundler/ruby/2.3.0/gems/factory_girl-4.8.0/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
# ./spec/models/market/stock_spec.rb:88:in `block (3 levels) in <top (required)>'
```

**Comment by nertzy** [comment]
Please try again with the Rails version locked to 5.1.2 and again with pg_search locked to 2.0.1 so we can figure out which upgrade triggered the error.

**Comment by KeithP** [comment]
With `gem 'rails', '5.1.2'` and `gem 'pg_search','2.0.1'` => tests pass
With `gem 'rails', '5.1.3'` and `gem 'pg_search','2.0.1'` => tests pass
With `gem 'rails', '5.1.2'` and `gem 'pg_search','2.1.0'` => tests fail
With `gem 'rails', '5.1.3'` and `gem 'pg_search','2.1.0'` => tests fail

It doesnt appear to be related to the Rails 5.1.3 upgrade

**Comment by chadrem** [comment]
I encountered this issue also. I was able to work around the problem by locking pg_search to 2.0.1 (instead of 2.1.0). Tested with both Rails 5.1.2 and 5.1.3.

**Comment by chadrem** [comment]
I was able to resolve my problem when using pg_search 2.1.0 with Rails 5.1.X. In my app's config/initializers/new_framework_defaults.rb I changed:

````Rails.application.config.active_record.belongs_to_required_by_default = false````

This was the default behavior in previous versions of rails. In Rails 5.X it's set to ````true```` by default.

I suspect the new pg_search 2.1.0 respects this setting with Rails 5 and that previous versions of pg_search (2.0.1) didn't. This is just a hunch as I haven't dug into the code.

You can read more about Rails 5 and how belongs_to associations required by default:
http://blog.bigbinary.com/2016/02/15/rails-5-makes-belong-to-association-required-by-default.html

@KeithP this one line change may resolve your problem and let you update both pg_search and rails without breaking your app.

**Comment by nertzy** [comment]
Thanks for the investigation! We don't do anything specific to address this setting in pg_search 2.1.0, but we start adding the Rails version to the generated migrations in pull request #362 so that might be what is triggering the new behavior.

**Comment by KeithP** [comment]
@chadrem thanks this resolved it. 
@nertzy strange if adding Rails version to the generated migrations caused this unintended consequence.
Many of the failures appeared to have no relation with pg_search... Maybe something flaky about belongs_to_required_by_default in active_record? 
Happy for this to be closed. Thank you.

**Comment by amarshall** [comment]
Closing since this appears to be due to ActiveRecord behavior.
