### ISSUE TITLE
Extensions PG::UndefinedTable: ERROR

### ISSUE THREAD

**Issue by Isoterik** [Casecommons/pg_search#453]
i am using the extensions as shown in the [wiki](https://github.com/Casecommons/pg_search/wiki/Installing-PostgreSQL-Extensions)
when i try to run a test i always get that error:

```
Error:
AddressTest#test_should_not_save_address_without_street:
DRb::DRbRemoteError: PG::UndefinedTable: ERROR:  relation "install_postgre_sql_extensions" does not exist
LINE 8:  WHERE a.attrelid = '"install_postgre_sql_extensions"'::regc...
                            ^
 (ActiveRecord::StatementInvalid)
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:65:in `exec'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:65:in `block (2 levels) in query'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.3.4/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.3.4/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.3.4/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:64:in `block in query'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract_adapter.rb:722:in `block (2 levels) in log'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract_adapter.rb:721:in `block in log'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.3.4/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract_adapter.rb:712:in `log'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:63:in `query'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/postgresql_adapter.rb:820:in `column_definitions'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/schema_statements.rb:114:in `columns'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/schema_cache.rb:76:in `columns'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/schema_cache.rb:82:in `columns_hash'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/model_schema.rb:488:in `load_schema!'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/attributes.rb:247:in `load_schema!'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/attribute_decorators.rb:50:in `load_schema!'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/model_schema.rb:478:in `block in load_schema'
    /home/isoterik/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/model_schema.rb:475:in `load_schema'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/model_schema.rb:357:in `columns'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/model_schema.rb:404:in `column_names'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/fixture_set/model_metadata.rb:25:in `timestamp_column_names'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/fixture_set/table_row.rb:79:in `fill_timestamps'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/fixture_set/table_row.rb:61:in `fill_row_model_attributes'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/fixture_set/table_row.rb:43:in `initialize'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/fixture_set/table_rows.rb:36:in `new'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/fixture_set/table_rows.rb:36:in `block in build_table_rows_from'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/fixture_set/table_rows.rb:35:in `each'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/fixture_set/table_rows.rb:35:in `map'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/fixture_set/table_rows.rb:35:in `build_table_rows_from'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/fixture_set/table_rows.rb:18:in `initialize'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/fixtures.rb:658:in `new'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/fixtures.rb:658:in `table_rows'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/fixtures.rb:603:in `block (2 levels) in insert'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/fixtures.rb:602:in `each'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/fixtures.rb:602:in `block in insert'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/fixtures.rb:599:in `each'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/fixtures.rb:599:in `insert'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/fixtures.rb:585:in `read_and_insert'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/fixtures.rb:545:in `create_fixtures'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/test_fixtures.rb:205:in `load_fixtures'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/test_fixtures.rb:118:in `setup_fixtures'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.3.4/lib/active_record/test_fixtures.rb:8:in `before_setup'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.3.4/lib/active_support/testing/setup_and_teardown.rb:40:in `before_setup'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/minitest-5.14.2/lib/minitest/test.rb:96:in `block (3 levels) in run'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/minitest-5.14.2/lib/minitest/test.rb:195:in `capture_exceptions'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/minitest-5.14.2/lib/minitest/test.rb:95:in `block (2 levels) in run'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/minitest-5.14.2/lib/minitest.rb:272:in `time_it'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/minitest-5.14.2/lib/minitest/test.rb:94:in `block in run'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/minitest-5.14.2/lib/minitest.rb:367:in `on_signal'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/minitest-5.14.2/lib/minitest/test.rb:211:in `with_info_handler'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/minitest-5.14.2/lib/minitest/test.rb:93:in `run'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/minitest-5.14.2/lib/minitest.rb:1029:in `run_one_method'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.3.4/lib/active_support/testing/parallelization.rb:89:in `block (3 levels) in start'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/minitest-5.14.2/lib/minitest.rb:367:in `on_signal'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/minitest-5.14.2/lib/minitest.rb:354:in `with_info_handler'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.3.4/lib/active_support/testing/parallelization.rb:88:in `block (2 levels) in start'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.3.4/lib/active_support/testing/parallelization.rb:75:in `fork'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.3.4/lib/active_support/testing/parallelization.rb:75:in `block in start'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.3.4/lib/active_support/testing/parallelization.rb:74:in `times'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.3.4/lib/active_support/testing/parallelization.rb:74:in `each'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.3.4/lib/active_support/testing/parallelization.rb:74:in `map'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.3.4/lib/active_support/testing/parallelization.rb:74:in `start'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/minitest-5.14.2/lib/minitest.rb:138:in `run'
    /home/isoterik/.rvm/gems/ruby-2.6.3/gems/minitest-5.14.2/lib/minitest.rb:68:in `block in autorun'
    /home/isoterik/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    /home/isoterik/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    -e:1:in `<main>'

```

**Comment by Isoterik** [comment]
fixed the issue. was my own fault.
i dont know why i created the migration file with the generation of a model named "install_postgre_sql_extensions".
after destroying it and creating a soley migration for the extensions the error dissappeared.
